<a href="https://colab.research.google.com/github/Enthusiasmile/Python_Codes/blob/main/Notes5(Numpy_%26_Pandas).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY

In [ ]:
l1=[1,2,3,2,52,5,5,2,5,8,5,8,5,8] 

In [ ]:
type(l1)

list

In [ ]:
import numpy as np #calling numpy #np is alia's name

In [ ]:
l2=np.array(l1) #converting any list into array #np.array()

In [ ]:
print(l2)

[ 1  2  3  2 52  5  5  2  5  8  5  8  5  8]


In [ ]:
type(l2) #ndarray= n dimensional array

numpy.ndarray

In [ ]:
l2.shape

(14,)

In [ ]:
la=[12,25,15,24] #multidimensional array / multinested array
lb=[22,11,45,66]
lc=[56,25,66,33]

In [ ]:
ld=np.array([la,lb,lc]) 

In [ ]:
print(ld)

[[12 25 15 24]
 [22 11 45 66]
 [56 25 66 33]]


In [ ]:
type(ld) #ndimensional here n=2 ie 2d array

numpy.ndarray

In [ ]:
ld.shape #shows no.of rows and columns in array.

(3, 4)

In [ ]:
print(ld.reshape(4,3)) #reshapes as per corresponding no.of rows and columns

[[12 25 15]
 [24 22 11]
 [45 66 56]
 [25 66 33]]


In [ ]:
ld.shape 

(3, 4)

In [ ]:
#indexing and slicing
print(l2)

[ 1  2  3  2 52  5  5  2  5  8  5  8  5  8]


In [ ]:
l2[7]

2

In [ ]:
l2[1:5]

array([ 2,  3,  2, 52])

In [ ]:
l2[::-1]

array([ 8,  5,  8,  5,  8,  5,  2,  5,  5, 52,  2,  3,  2,  1])

In [ ]:
print(ld)

[[12 25 15 24]
 [22 11 45 66]
 [56 25 66 33]]


In [ ]:
ld[0:2,1:3] #before(,)for rows..after(,)for columns

array([[25, 15],
       [11, 45]])

my_list1=[4,5,6,7,8]


my_list2=[-2,6,8,3,4]


my_list3=[5,6,0,-3,5]

Convert these lists into a multinested array and fetch the given rows and columns

1. arr=[0:2,2:]
2. arr=[0:2,0:2]
3. arr=[1:,:4]

In [ ]:
my_list1=[4,5,6,7,8]

my_list2=[-2,6,8,3,4]

my_list3=[5,6,0,-3,5]

In [ ]:
my_list4=np.array([my_list1,my_list2,my_list3])
print(my_list4)

[[ 4  5  6  7  8]
 [-2  6  8  3  4]
 [ 5  6  0 -3  5]]


In [ ]:
my_list4[0:2,2: ]

array([[6, 7, 8],
       [8, 3, 4]])

In [ ]:
my_list4[0:2,0:2]

array([[ 4,  5],
       [-2,  6]])

In [ ]:
my_list4[1:,:4]

array([[-2,  6,  8,  3],
       [ 5,  6,  0, -3]])

In [ ]:
#generating numbers
arr1=np.arange(1,10) #equally spaced range from 1-9. here 1 is stepsize by default 
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [ ]:
arr2=np.arange(1,20,2) #2 is stepsize
print(arr2)

[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
np.arange(3,31,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [ ]:
np.linspace(1,10) #create 50 unique elements in range of 1-10 (50=by default)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [ ]:
np.linspace(1,10,20) #create 20 unique elements in range of 1-10

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [ ]:
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [ ]:
np.random.rand(7,4) #7=no.of rows,4=no.of columns from range 0-1,1=exclusive

array([[0.72762511, 0.70337816, 0.86433018, 0.62656388],
       [0.82509732, 0.62342916, 0.96587057, 0.54052872],
       [0.53383267, 0.45160236, 0.26177953, 0.92646476],
       [0.2104616 , 0.67026306, 0.87229393, 0.40710113],
       [0.40929593, 0.63048043, 0.79374833, 0.840385  ],
       [0.94610516, 0.60662715, 0.24328174, 0.20727415],
       [0.4000288 , 0.40513897, 0.38594022, 0.13209885]])

In [ ]:
np.random.rand(5,5)

array([[0.68859313, 0.42102092, 0.2145782 , 0.33367883, 0.94964432],
       [0.31722742, 0.88398744, 0.39125869, 0.04764898, 0.64561172],
       [0.01494978, 0.2546009 , 0.74213625, 0.65114838, 0.50399703],
       [0.85179744, 0.50471168, 0.81253299, 0.7679004 , 0.56710979],
       [0.64230701, 0.28527435, 0.23490894, 0.31729363, 0.18695054]])

In [ ]:
np.random.randint(1,10,20) #1-10 is range 20=no.of random elements

array([5, 1, 9, 4, 6, 3, 6, 4, 8, 7, 6, 5, 3, 9, 3, 7, 4, 9, 5, 5])

PANDAS
1. Loading and reading the data

2. Statistical analysis of data

3. Creating the structure of dummy dataset

In [ ]:
import pandas as pd #pd is the alias name

In [ ]:
data=pd.read_csv('/tips[1].csv') #uploading the file

In [ ]:
data.head() #shows 1st 5 rows of dataset by default

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
data.tail() #shows last 5 rows of dataset by default

total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [ ]:
data.head(10) #shows the first 10 rows from the dataset

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

In [ ]:
data.tail(10) #shows the last 10 rows from the dataset

total_bill   tip     sex smoker   day    time  size
234       15.53  3.00    Male    Yes   Sat  Dinner     2
235       10.07  1.25    Male     No   Sat  Dinner     2
236       12.60  1.00    Male    Yes   Sat  Dinner     2
237       32.83  1.17    Male    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [ ]:
data.info() #information about dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object 
 3   smoker      244 non-null    object 
 4   day         244 non-null    object 
 5   time        244 non-null    object 
 6   size        244 non-null    int64  
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB


In [ ]:
data.describe() #shows statistical parameters w.r.to numerical columns

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [ ]:
#creating a dummy dataset

In [ ]:
my_data=pd.DataFrame(np.arange(0,20).reshape(4,5),index=['row1','row2','row3','row4'],columns=['col1','col2','col3','col4','col5'])
print(my_data)

      col1  col2  col3  col4  col5
row1     0     1     2     3     4
row2     5     6     7     8     9
row3    10    11    12    13    14
row4    15    16    17    18    19


In [ ]:
#saving dummy dataset
my_data.to_csv('demo_topmentor') #for csv file

In [ ]:
my_data.to_excel('demo_topmento.xlsx') #foe excel file

In [ ]:
#fetching values from the dataset - iloc[]
my_data.iloc[0:3,1:4]   

col2  col3  col4
row1     1     2     3
row2     6     7     8
row3    11    12    13